[-
 use CGI::Cookie;
 use Digest::MD5 qw(md5_hex);

 use HDS::DBI;
 use HDS::User;
 use HDS::Category;

 $cat         = undef;
 $user        = undef;
 %cookie_jar  = CGI::Cookie->fetch($r);
 $user_access = 0;
 $success     = 0;
 $message     = "No information available";
 $content     = "No information available";
 $sep_char    = "~~~~~";
 
if (exists $cookie_jar{'user_id'} && $cookie_jar{'user_id'}->value ne "") {
   $user = HDS::User->retrieve($cookie_jar{'user_id'}->value);
}

if ($user) {
   if ($fdat{cat_id}) {
      $cat = HDS::Category->retrieve($fdat{cat_id});
   }
   if ($cat) {
      $cat->name($fdat{name});
      $cat->description($fdat{description});
      $cat->access($fdat{access_id});
      $cat->is_active($fdat{is_active});
      $cat->update();

      $success = 1;
      $message = "<blockquote><b>Category successfully edited.</b></blockquote>";
      $content = $fdat{name} . $sep_char . 
          $fdat{description} . $sep_char . 
          $cat->access->name;
   }
   else {
      $message = "Category does not exist.  Please refresh the page.";
   }
}
-][- $old_escmode = $escmode; $escmode = 0; -][+ $success +][+ $sep_char +][+ $message +][+ $sep_char +][+ $content +][- $escmode = $old_escmode; -]
