[-
 use CGI::Cookie;
 use Digest::MD5 qw(md5_hex);

 use HDS::DBI;
 use HDS::User;
 use HDS::WebContent;

 $web         = undef;
 $user        = undef;
 %cookie_jar  = CGI::Cookie->fetch($r);
 $user_access = 0;
 $success     = 0;
 $message     = "No information available";
 $content     = "No information available";
 $sep_char    = "~~~~~";
 
if (exists $cookie_jar{'user_id'} && $cookie_jar{'user_id'}->value ne "") {
   $user = HDS::User->retrieve($cookie_jar{'user_id'}->value);
}

if ($user) {
   if ($fdat{content_id}) {
      $web = HDS::WebContent->retrieve($fdat{content_id});
   }
   if ($web) {
      $web->content($fdat{content_html});
      $web->content_order($fdat{content_order});
      $web->access($fdat{access_id});
      #$web->is_active($fdat{is_active});

      $web->update();

      $success = 1;
      $message = "<blockquote><b>WebContent successfully edited.</b></blockquote>";
      $content = $fdat{content_html} . $sep_char . 
          $web->access->name;
   }
   else {
      $message = "WebContent does not exist.  Please refresh the page.";
   }
}
-][- $old_escmode = $escmode; $escmode = 0; -][+ $success +][+ $sep_char +][+ $message +][+ $sep_char +][+ $content +][- $escmode = $old_escmode; -]
