[-
 use CGI::Cookie;

 use HDS::DBI;
 use HDS::User;
 use HDS::WebContent;

 $web     = undef;
 $user    = undef;
 %cookie_jar = CGI::Cookie->fetch($r);
 $user_access = 0;
 $success     = 0;
 $message     = "No information available";
 $content     = "No information available";
 $sep_char    = "~~~~~";
 
if (exists $cookie_jar{'user_id'} && $cookie_jar{'user_id'}->value ne "") {
   $user = HDS::User->retrieve($cookie_jar{'user_id'}->value);
}

if ($user) {
   $web = HDS::WebContent->insert({content   => $fdat{content_html},
                                   content_order   => $fdat{content_order},
                                   #page     => $fdat{content_page},
                                   #section  => $fdat{content_section},
                                   access    => $fdat{access_id},
                                   #is_active => 1,
                                });
   if ($web) {
      $success = 1;
      $message = "Home page content created successfully.";
      $content = '<tr><td>&nbsp;</td>' .
          '<td id="display_content_access_'. $web->id .'">'. $web->access->name .'</td>' .
          '<td><div id="display_content_html_'. $web->id .'" class="web_content">'. 
          $web->content .'</div></td></tr>';
   }
   else {
      $message = "Home page content NOT added.  Please try again.";
   }
}
-][- $old_escmode = $escmode; $escmode = 0; -][+ $success +][+ $sep_char +][+ $message +][+ $sep_char +][+ $content +][- $escmode = $old_escmode; -]
