[-

use CGI;
use Data::Dumper;
use CGI::Cookie;
use IO::File;

use HDS::DBI;
use HDS::User;
use HDS::Access;
use HDS::Document;

$user       = undef;
$doc        = undef;
%cookie_jar = CGI::Cookie->fetch($r);
$file_name  = time();
$file_ext   = "";
$file_info  = {};
$doc_dir    = "$ENV{SVR_HOME}/files/hideaway/$ENV{SVR_NAME}";
$db_now     = HDS::DBI::db_now();
$bytes      = 0;
$sep_char   = "~~~~~";
$success    = 0;
$message    = '';
$content    = '';

if (exists $cookie_jar{'user_id'} && $cookie_jar{'user_id'}->value ne "") {
   $user = HDS::User->retrieve($cookie_jar{'user_id'}->value);
}

if ($user) {
   $doc = HDS::Document->retrieve($fdat{doc_id});
   if ($doc) {
      if ($fdat{'upload_file'}) {
         $file_info = $fdat{'-upload_file'};
         
         $file_ext = $fdat{'upload_file'};
         $file_ext =~ s/^(.*)\.(\w+)$/$2/;
         $file_ext = lc $file_ext;
         
         # Store the file
         my $buffer;
         open FILE, "> $doc_dir/$file_name\.$file_ext";
         binmode FILE;
         while (read($fdat{'upload_file'},$buffer,32768)) {
            print FILE $buffer;
         }
         close(FILE);
         
         $bytes = (stat("$doc_dir/$file_name\.$file_ext"))[7];
         
         if ($bytes > 0) {
            if (-f "$doc_dir/".$doc->file_path) {
               unlink "$doc_dir/".$doc->file_path;
            }

	    my $real_name = $fdat{'upload_file'};
	    if ($real_name =~ /^.*\\(.*?)\.(\w+)$/) {
	       $real_name = $1 . '.' . $2;
	    }
            
            # Update the Document object
            $doc->modify_date($db_now);
            $doc->owner($user->id);
            $doc->mime_type($fdat{'-upload_file'}->{'Content-Type'});
            $doc->bytes($bytes);
            #$doc->file_name($fdat{upload_file});
	    $doc->file_name($real_name);
            $doc->file_path("$file_name\.$file_ext");
            $doc->download_count(0);
            $doc->update();
            
            $success = 1;
            $message = 'Document <a href="javascript:;" onClick="doc_download(' . 
                $doc->id . '); return false;">' . $doc->title .'</a> replaced successfully.';
         }
      }
   }
   else {
      $message = "Document does not exist.  Please refresh page.";
   }
}
-][- $old_escmode = $escmode; $escmode = 0; -][+ $success +][+ $sep_char +][+ $message +]

