[-
 use CGI::Cookie;
 use Digest::MD5 qw(md5_hex);

 use HDS::DBI;
 use HDS::User;

 $usr         = undef;
 $user        = undef;
 $pass_crypt  = "";
 %cookie_jar  = CGI::Cookie->fetch($r);
 $user_access = 0;
 $success     = 0;
 $message     = "No information available";
 $sep_char    = "~~~~~";
 
if (exists $cookie_jar{'user_id'} && $cookie_jar{'user_id'}->value ne "") {
   $user = HDS::User->retrieve($cookie_jar{'user_id'}->value);
}

if ($user) {
   if ($fdat{access_id} && $fdat{username} && $fdat{password}) {
      my @dups = HDS::User->search({username => $fdat{username}});
      if (scalar @dups > 0) {
         $message = "Username $fdat{username} already exists.";
      }
      else {
         $pass_crypt = md5_hex($fdat{password});  # Well, not really encrypted
         $usr = HDS::User->insert({username    => $fdat{username},
                                   password    => $pass_crypt,
                                   full_name   => $fdat{full_name},
                                   email       => $fdat{email},
                                   phone1      => $fdat{phone1},
                                   phone2      => $fdat{phone2},
                                   access      => $fdat{access_id},
                                   is_active   => $fdat{is_active},
                                   change_passwd => $fdat{change_passwd},
                                     });
         if ($usr) {
            $success = 1;
            $message = "User $fdat{full_name} ($fdat{username}) created successfully.";
         }
      }
   }
   else {
      $message = "Username, Password and Access are required.";
   }
}
-][- $old_escmode = $escmode; $escmode = 0; -][+ $success +][+ $sep_char +][+ $message +][+ $sep_char +]
[$ if ($success) $]
	<tr>
	<td><div id="display_user_username_[+ $usr->id +]"> [+ $usr->username +]</div></td>
	<td style="-ms-filter:progid:DXImageTransform.Microsoft.Alpha(Opacity=50); filter: alpha(opacity=50); opacity: .5;">
<a href="javascript:;" onClick="alert('Please refresh this page.'); /*user_take_action('[+ $usr->id +]', 'edit');*/" title="Edit [+ $usr->username +]"><img src="images/user_edit.gif" border=0></a>
	<a href="javascript:;" onClick="alert('Please refresh this page.'); /*user_take_action('[+ $usr->id +]', 'inactive');*/" title="Make [+ $usr->username +] Inactive"><img id="user_active_img_[+ $usr->id +]" src="images/user_has_access.gif" border=0></a>
	<a href="javascript:;" onClick="alert('Please refresh this page.'); /*user_take_action('[+ $usr->id +]', 'delete');*/" title="Delete [+ $usr->username +]"><img src="images/user_delete.gif" border=0></a>
	</td>
	<td><div id="display_user_full_name_[+ $usr->id +]">[+ $usr->full_name +]</div></td>
	<td><div id="display_user_access_[+ $usr->id +]">[+ $usr->access->name +]</div></td>
	</tr>
	<tr>
	<td colspan=4><div class="edit_win" id="user_edit_[+ $usr->id +]"></div>
	</td></tr>
[$ endif $][- $escmode = $old_escmode; -]
