[-
 use CGI::Cookie;
 use Digest::MD5 qw(md5_hex);

 use HDS::DBI;
 use HDS::User;

 $user        = undef;
 $pass_crypt  = "";
 $success     = 0;
 $message     = "No information available";
 $content     = "No information available";
 $sep_char    = '|';
 
 if ($fdat{user_id}) {
    $user = HDS::User->retrieve($fdat{user_id});
    if ($user) {
       $pass_crypt = md5_hex($fdat{new_password});  # Well, not really encrypted
       $user->password($pass_crypt);
       $user->change_passwd(0);
       $user->update();
       $success = 1;
       #$message = "<blockquote><b>Password successfully changed.</b></blockquote>";
       $message = $user->id . $sep_char . $user->full_name . 
           "<img src=\"/images/loading2.gif\">Please wait...";
       $content = "...please wait";
    }
    else {
       $message = "User does not exist.  Please refresh the page.";
    }
 }
 else {
    $message = "Please provide your username.";
 }
    
-][- $old_escmode = $escmode; $escmode = 0; -][+ $success +][+ $sep_char +][+ $message +][+ $sep_char +][+ $content +][- $escmode = $old_escmode; -]
